spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_demo?useSSL=false
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:9000/userinfo
